#include <iostream>
#include <windows.h>
#include <unistd.h>
using namespace std;
main()
{
	while(true)
	{
		
		cout<<"                       # # #                                        "<<endl;
		cout<<"                           #                                        "<<endl;
		cout<<"                           #                                        "<<endl;
		cout<<"                       # # #                                        "<<endl;
		cout<<"                           #                                        "<<endl;
		cout<<"                           #                                        "<<endl;
		cout<<"                       # # #                                        "<<endl;
		Sleep(1000);
	    system("cls");
	    
	    cout<<"                       # # #                                        "<<endl;
		cout<<"                           #                                        "<<endl;
		cout<<"                           #                                        "<<endl;
		cout<<"                       # # #                                        "<<endl;
		cout<<"                       #                                            "<<endl;
		cout<<"                       #                                            "<<endl;
		cout<<"                       # # #                                        "<<endl;
		Sleep(1000);
	    system("cls");
	    
	    cout<<"                         #                                          "<<endl;
		cout<<"                        ##                                          "<<endl;
		cout<<"                       # #                                          "<<endl;
		cout<<"                         #                                          "<<endl;
		cout<<"                         #                                          "<<endl;
		cout<<"                         #                                          "<<endl;
		cout<<"                       # # #                                        "<<endl;
		Sleep(1000);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|  i kill you                              |___|               "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(1000);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                     no   |___|               "<<endl;
		cout<<"  | |   ____                                     | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
	    Sleep(1000);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____/*  -->                              | |                "<<endl;
		cout<<"  | |---|   \\*                                   | |               "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(800);
	    system("cls");
	    
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____        -->                          | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____             -->                     | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____                  -->                | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____                      -->            | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____                           -->       | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
	    
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____                                -->  | |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
		
		cout<<" _____                                          _____               "<<endl;
		cout<<" |  *|                                          |*  |               "<<endl;
		cout<<" |___|                                          |___|               "<<endl;
		cout<<"  | |   ____                                     / |                "<<endl;
		cout<<"  | |---|                                        | |                "<<endl;
		cout<<"  |_|                                            |_|                "<<endl;
		cout<<"  | |                                            | |                "<<endl;
		Sleep(500);
	    system("cls");
		
		cout<<" _____                                                              "<<endl;
		cout<<" |  *|                                                              "<<endl;
		cout<<" |___|                                                              "<<endl;
		cout<<"  | |   ____                                                        "<<endl;
		cout<<"  | |---|                                                           "<<endl;
		cout<<"  |_|                                            __ _____ __        "<<endl;
		cout<<"  | |                                            __|_____|__|       "<<endl;
		Sleep(500);
	    system("cls");
	
		cout<<"                                                     _____          "<<endl;
		cout<<"                                                     |*  |          "<<endl;
		cout<<" _____                                               |___|          "<<endl;
		cout<<" |  *|                                                |  |          "<<endl;
		cout<<" |___|                                                |__| soul    "<<endl;
		cout<<"  | |   ____                                                        "<<endl;
		cout<<"  | |---|                                                           "<<endl;
		cout<<"  |_|                                            __ _____ __        "<<endl;
		cout<<"  | |                                            __|_____|__|       "<<endl;
	    Sleep(1000);
	    system("cls");
	    
		cout<<"                                                     _____          "<<endl;
		cout<<"                                                     |*  |          "<<endl;
		cout<<"                                                     |___|          "<<endl;
		cout<<" _____                                                |  |          "<<endl;
		cout<<" |  *|                                                |__|          "<<endl;
		cout<<" |___|                                                              "<<endl;
		cout<<"  | |   ____                                                        "<<endl;
		cout<<"  | |---|                                                           "<<endl;
		cout<<"  |_|                                            __ _____ __        "<<endl;
		cout<<"  | |                                            __|_____|__|       "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
		cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<" _____                                                |__|          "<<endl;
		cout<<" |  *|                                                              "<<endl;
		cout<<" |___|                                                              "<<endl;
		cout<<"  | |   ____                                                        "<<endl;
		cout<<"  | |---|                                                           "<<endl;
		cout<<"  |_|                                            __ _____ __        "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<" _____                                                              "<<endl;
		cout<<" |  *|                                                              "<<endl;
		cout<<" |___|                                                              "<<endl;
		cout<<"  | |   ____                                                        "<<endl;
		cout<<"  | |---|                                                           "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<" _____                                                              "<<endl;
		cout<<" |  *|                                                              "<<endl;
		cout<<" |___|                                                              "<<endl;
		cout<<"  | |   ____                                                        "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<" _____                                                              "<<endl;
		cout<<" |  *|                                                              "<<endl;
		cout<<" |___|                                                              "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<endl;
		cout<<" _____                                                              "<<endl;
		cout<<" |  *|                                                              "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<endl;
		cout<<endl;
		cout<<" _____                                                              "<<endl;
	    Sleep(200);
	    system("cls");
	    
	    cout<<"                                                     _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<endl;
		cout<<endl;
		cout<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"   \\------------/                                    _____          "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<endl;
		cout<<endl;
		cout<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"   /------------\\                                                  "<<endl;
	    cout<<"   \\------------/                                    _____         "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<endl;
		cout<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"      |_\\ |_\\                                                       "<<endl;
	    cout<<"   /------------\\                                                  "<<endl;
	    cout<<"   \\------------/                                    _____         "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
		cout<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      |_\\ |_\\                                                       "<<endl;
	    cout<<"   /------------\\                                                  "<<endl;
	    cout<<"   \\------------/                                    _____         "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
		cout<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      |_\\ |_\\                                                     "<<endl;
	    cout<<"   /------------\\                                                  "<<endl;
	    cout<<"   \\------------/                                    _____         "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
		cout<<"                                                                    "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"     |_______|                                                      "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      |_\\ |_\\                                                     "<<endl;
	    cout<<"   /------------\\                                                  "<<endl;
	    cout<<"   \\------------/                                    _____         "<<endl;
	    cout<<"                                                     |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |_______|                                                      "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      |_\\ |_\\                                                     "<<endl;
	    cout<<"   /------------\\                                    _____         "<<endl;
	    cout<<"   \\------------/                                    |*  |          "<<endl;
	    cout<<"                                                     |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |_______|                                                      "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      |_\\ |_\\                                        _____        "<<endl;
	    cout<<"   /------------\\                                    |*  |          "<<endl;
	    cout<<"   \\------------/                                    |___|          "<<endl;
		cout<<"                                                      |  |          "<<endl;
		cout<<"                                                      |__|          "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |_______|                                                      "<<endl;
	    cout<<"      | | | |                                                       "<<endl;
	    cout<<"      | | | |                                        _____          "<<endl;
	    cout<<"      |_\\ |_\\                                        |*  |        "<<endl;
	    cout<<"   /------------\\                                    |___|         "<<endl;
		cout<<"   \\------------/                                     |  |         "<<endl;
		cout<<"                                                      |__|          "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"     ___| |___                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |_______|                                                      "<<endl;
	    cout<<"      | | | |                                        _____          "<<endl;
	    cout<<"      | | | |                                        |*  |          "<<endl;
	    cout<<"      |_\\ |_\\                                        |___|        "<<endl;
		cout<<"   /------------\\                                     |  |         "<<endl;
		cout<<"   \\------------/                                     |__|         "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"       |___|                                                      "<<endl;
	    cout<<"     ___| |___                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |       |                                                      "<<endl;
	    cout<<"     |_______|                                       _____          "<<endl;
	    cout<<"      | | | |                                        |*  |          "<<endl;
	    cout<<"      | | | |                                        |___|        "<<endl;
		cout<<"      |_\\ |_\\                                         |  |         "<<endl;
		cout<<"   /------------\\                                     |__|         "<<endl;
	    Sleep(300);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                      "<<endl;
	    cout<<"||===|       |                                                      "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                         Is this hell ? /___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(5000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___\\  No, you're a good soul.                               "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                      "<<endl;
	    cout<<"||===|       |===(                                                 "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(5000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |     \\ /                                                "<<endl;
	    cout<<"||===|       |===(  o                                               "<<endl;
	    cout<<"||   |       |     / \\                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |    _| |_                                                "<<endl;
	    cout<<"||===|       |===(_ O _                                             "<<endl;
	    cout<<"||   |       |     | |                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |     \\ /                                                "<<endl;
	    cout<<"||===|       |===(  o                                               "<<endl;
	    cout<<"||   |       |     / \\                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |    _| |_                                                "<<endl;
	    cout<<"||===|       |===(_ O _                                             "<<endl;
	    cout<<"||   |       |     | |                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |     \\ /                                                "<<endl;
	    cout<<"||===|       |===(  o                                               "<<endl;
	    cout<<"||   |       |     / \\                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |    _| |_                                                "<<endl;
	    cout<<"||===|       |===(_ O _                                             "<<endl;
	    cout<<"||   |       |     | |                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |     \\ /                                                "<<endl;
	    cout<<"||===|       |===(  o                                               "<<endl;
	    cout<<"||   |       |     / \\                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |    _| |_                                                "<<endl;
	    cout<<"||===|       |===(_ O _                                             "<<endl;
	    cout<<"||   |       |     | |                               _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(    O                                               "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(      O                                               "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(        O                                        "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(          O                                     "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(            O                                   "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(              O                                   "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(                O                                   "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(                    O                                   "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                       \\ /                                 "<<endl;
	    cout<<"||===|       |===(                    O                                   "<<endl;
	    cout<<"||   |       |                       / \\             _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(500);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                      \\   /                               "<<endl;
	    cout<<"||   |       |                       \\ /                                 "<<endl;
	    cout<<"||===|       |===(                    O                                   "<<endl;
	    cout<<"||   |       |                       / \\             _____          "<<endl;
	    cout<<"||   |_______|                      /   \\            |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(800);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                   "<<endl;
	    cout<<"||   |       |                                                     "<<endl;
	    cout<<"||===|       |===(                   ()                                   "<<endl;
	    cout<<"||   |       |                                       _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                   "<<endl;
	    cout<<"||   |       |                       /\\                             "<<endl;
	    cout<<"||===|       |===(                  (  )                                   "<<endl;
	    cout<<"||   |       |                       \\/              _____          "<<endl;
	    cout<<"||   |_______|                                       |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(1000);                                                           
	    system("cls");                                                                
	                                                                        
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                       /\\                            "<<endl;
	    cout<<"||   |       |                      {  }                           "<<endl;
	    cout<<"||===|       |===(                 (    )                                   "<<endl;
	    cout<<"||   |       |                      {  }             _____          "<<endl;
	    cout<<"||   |_______|                       \\/              |*  |          "<<endl;
	    cout<<"||    | | | |                                        |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\                            "<<endl;
	    cout<<"||   |       |                     {    }                           "<<endl;
	    cout<<"||===|       |===(                (      )                                   "<<endl;
	    cout<<"||   |       |                     {    }            _____          "<<endl;
	    cout<<"||   |_______|                      \\  /             |*  |          "<<endl;
	    cout<<"||    | | | |                        \\/              |___|        "<<endl;
		cout<<"||    | | | |                                         |  |         "<<endl;
		cout<<"||    |_\\ |_\\                                         |__|         "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\                            "<<endl;
	    cout<<"||   |       |                     {    }                           "<<endl;
	    cout<<"||===|       |===(                (      )           _____         "<<endl;
	    cout<<"||   |       |                     {    }            |*  |          "<<endl;
	    cout<<"||   |_______|                      \\  /             |___|          "<<endl;
	    cout<<"||    | | | |                        \\/               |  |        "<<endl;
		cout<<"||    | | | |                                         |__|         "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\                            "<<endl;
	    cout<<"||   |       |                     {    }            _____               "<<endl;
	    cout<<"||===|       |===(                (      )           |*  |         "<<endl;
	    cout<<"||   |       |                     {    }            |___|          "<<endl;
	    cout<<"||   |_______|                      \\  /              |  |          "<<endl;
	    cout<<"||    | | | |                        \\/               |__|        "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\             _____           "<<endl;
	    cout<<"||   |       |                     {    }            |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )           |___|         "<<endl;
	    cout<<"||   |       |                     {    }             |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /              |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\            _____           "<<endl;
	    cout<<"||   |       |                     {    }           |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )          |___|         "<<endl;
	    cout<<"||   |       |                     {    }            |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /             |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\           _____           "<<endl;
	    cout<<"||   |       |                     {    }          |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )         |___|         "<<endl;
	    cout<<"||   |       |                     {    }           |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /            |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\          _____           "<<endl;
	    cout<<"||   |       |                     {    }         |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )        |___|         "<<endl;
	    cout<<"||   |       |                     {    }          |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /           |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\         _____           "<<endl;
	    cout<<"||   |       |                     {    }        |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )       |___|         "<<endl;
	    cout<<"||   |       |                     {    }         |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /          |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\        _____           "<<endl;
	    cout<<"||   |       |                     {    }       |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )      |___|         "<<endl;
	    cout<<"||   |       |                     {    }        |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /         |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\       _____           "<<endl;
	    cout<<"||   |       |                     {    }      |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )     |___|         "<<endl;
	    cout<<"||   |       |                     {    }       |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /        |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\      _____           "<<endl;
	    cout<<"||   |       |                     {    }     |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )    |___|         "<<endl;
	    cout<<"||   |       |                     {    }      |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /       |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\    _____           "<<endl;
	    cout<<"||   |       |                     {    }   |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )  |___|         "<<endl;
	    cout<<"||   |       |                     {    }    |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /     |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\  _____           "<<endl;
	    cout<<"||   |       |                     {    } |*  |               "<<endl;
	    cout<<"||===|       |===(                (      )|___|         "<<endl;
	    cout<<"||   |       |                     {    }  |  |          "<<endl;
	    cout<<"||   |_______|                      \\  /   |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\_____           "<<endl;
	    cout<<"||   |       |                     {    }*  |               "<<endl;
	    cout<<"||===|       |===(                (      )__|         "<<endl;
	    cout<<"||   |       |                     {    }|  |          "<<endl;
	    cout<<"||   |_______|                      \\  / |__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\___           "<<endl;
	    cout<<"||   |       |                     {    } |               "<<endl;
	    cout<<"||===|       |===(                (      )|         "<<endl;
	    cout<<"||   |       |                     {    } |          "<<endl;
	    cout<<"||   |_______|                      \\  /__|          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                      Heaven                              "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\           "<<endl;
	    cout<<"||   |       |                     {    }               "<<endl;
	    cout<<"||===|       |===(                (      )         "<<endl;
	    cout<<"||   |       |                     {    }          "<<endl;
	    cout<<"||   |_______|                      \\  /          "<<endl;
	    cout<<"||    | | | |                        \\/                       "<<endl;
		cout<<"||    | | | |                                                   "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                         /\\                             "<<endl;
	    cout<<"||   ___| |___                      /  \\                            "<<endl;
	    cout<<"||   |       |                     {    }                           "<<endl;
	    cout<<"||===|       |===(                (      )                                   "<<endl;
	    cout<<"||   |       |                     {    }                    "<<endl;
	    cout<<"||   |_______|                      \\  /                      "<<endl;
	    cout<<"||    | | | |                        \\/                    "<<endl;
		cout<<"||    | | | |                                               "<<endl;
		cout<<"||    |_\\ |_\\                                                "<<endl;
		Sleep(1000);
	    system("cls");
	    
		cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                       /\\                            "<<endl;
	    cout<<"||   |       |                      {  }                           "<<endl;
	    cout<<"||===|       |===(                 (    )                                   "<<endl;
	    cout<<"||   |       |                      {  }                     "<<endl;
	    cout<<"||   |_______|                       \\/                      "<<endl;
	    cout<<"||    | | | |                                              "<<endl;
		cout<<"||    | | | |                                                "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                   "<<endl;
	    cout<<"||   |       |                       /\\                             "<<endl;
	    cout<<"||===|       |===(                  (  )                                   "<<endl;
	    cout<<"||   |       |                       \\/                       "<<endl;
	    cout<<"||   |_______|                                               "<<endl;
	    cout<<"||    | | | |                                              "<<endl;
		cout<<"||    | | | |                                                "<<endl;
		cout<<"||    |_\\ |_\\                                                 "<<endl;
	    Sleep(1000);                                                           
	    system("cls"); 
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                   "<<endl;
	    cout<<"||   |       |                                                     "<<endl;
	    cout<<"||===|       |===(                   ()                                   "<<endl;
	    cout<<"||   |       |                                                 "<<endl;
	    cout<<"||   |_______|                                                 "<<endl;
	    cout<<"||    | | | |                                                "<<endl;
		cout<<"||    | | | |                                                  "<<endl;
		cout<<"||    |_\\ |_\\                                                  "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(                    O                                   "<<endl;
	    cout<<"||   |       |                                                "<<endl;
	    cout<<"||   |_______|                                               "<<endl;
	    cout<<"||    | | | |                                              "<<endl;
		cout<<"||    | | | |                                               "<<endl;
		cout<<"||    |_\\ |_\\                                                "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	    cout<<"       _____                                                    "<<endl;
	    cout<<"\\/     |  *|                                                      "<<endl;
	    cout<<"||     |___|                                                      "<<endl;
	    cout<<"||   ___| |___                                                      "<<endl;
	    cout<<"||   |       |                                                       "<<endl;
	    cout<<"||===|       |===(                                                       "<<endl;
	    cout<<"||   |       |                                                "<<endl;
	    cout<<"||   |_______|                                               "<<endl;
	    cout<<"||    | | | |                                              "<<endl;
		cout<<"||    | | | |                                               "<<endl;
		cout<<"||    |_\\ |_\\                                                "<<endl;
	    Sleep(1000);
	    system("cls");
	    
	}
}